const recipes = [
  {
    name: "Spaghetti Carbonara",
    ingredients: ["Pasta", "Bacon", "Eggs", "Cheese"],
    steps: [
      "Boil pasta until al dente.",
      "Cook bacon until crispy.",
      "Mix eggs and cheese in a bowl.",
      "Combine pasta with bacon, eggs, and cheese.",
    ],
    spiciness: "Medium Hot",
    categories: ["Italian"],
  },
  {
    name: "Margherita Pizza",
    ingredients: ["Tomato Sauce", "Pizza Dough", "Mozzarella", "Basil"],
    steps: [
      "Spread tomato sauce on prepared pizza dough.",
      "Top with slices of mozzarella and fresh basil.",
      "Bake in preheated oven at 220C for 15 minutes.",
    ],
    spiciness: "Mild",
    categories: ["Italian", "Fast Food"],
  },
  {
    name: "Chicken Curry",
    ingredients: ["Chicken", "Curry Powder", "Coconut Milk"],
    steps: [
      "Brown chicken pieces in a skillet.",
      "Pour in coconut milk and simmer until chicken is cooked through.",
      "Beat Cream Cheese.",
    ],
    spiciness: "Inferno",
    categories: ["Indian"],
  },
  {
    name: "Cheesecake",
    ingredients: [
      "Condensed milk",
      "Cream Cheese",
      "Lemon Juice",
      "Pie Crust",
      "Cherry Jam",
    ],
    steps: [
      "Beat Cream Cheese.",
      "Add condensed milk and blend.",
      "Add Lemon Juice and blend.",
      "Add the mix to the pie crust.",
      "Spread the Cherry Jam.",
      "Place in refrigerator for 3 hours.",
    ],
    spiciness: "Mild",
    categories: ["No-Bake", "Vegetarian", "Cake"],
  },
  {
    name: "Roasted Brussels Sprouts",
    ingredients: [
      "Brussels Sprouts",
      "Sesame seeds",
      "Olive oil",
      "Salt",
      "Lemon juice",
      "Pepper",
    ],
    steps: [
      "Preheat the oven.",
      "Mix the ingredients in a bowl.",
      "Spread the mix on baking sheet.",
      "Bake for 30 minutes.",
    ],
    spiciness: "Extra Hot",
    categories: ["Vegan", "Gluten-free"],
  },
  {
    name: "Mac & Cheese",
    ingredients: [
      "Butter",
      "Flour",
      "Macaroni",
      "Shredded Cheddar cheese",
      "Salt",
      "Pepper",
    ],
    steps: [
      "Cook Macaroni.",
      "Melt butter in a saucepan.",
      "Add flour, salt, pepper and mix.",
      "Add milk and mix.",
      "Cook until mix is smooth.",
      "Add cheddar cheese.",
      "Add the macaroni.",
    ],
    spiciness: "Mild",
    categories: ["Vegetarian"],
  },
  {
    name: "Tamagoyaki Japanese Omelette",
    ingredients: ["Olive oil", "Soy sauce", "Sugar", "Salt", "Eggs"],
    steps: [
      "Beat the eggs.",
      "Add soy sauce, sugar and salt.",
      "Add oil to a saucepan.",
      "Bring to medium heat.",
      "Add some mix to the saucepan.",
      "Let it cook for 1 minute.",
      "Add oil to a saucepan.",
      "Add some mix to the saucepan.",
      "Let it cook for 1 minute.",
      "Remove pan from fire.",
    ],
    spiciness: "Mild",
    categories: ["Japanese", "Vegetarian"],
  },
];

export default recipes;
